"""
04_figures.py — All thesis figures, generated by one script.

Reads CSVs from data/, the activation matrices, and the network edge lists.

Figures produced
----------------
Result figures (data/ CSVs + activation matrices):
  fig_topology.pdf              — ASPL, CC_unweighted  (SQ1)
  fig_gender_bias.pdf           — Wilcoxon effect sizes, F and M targets
  fig_lme_forest.pdf            — Per-network LME β for weighted_path_z  (SQ2)
  fig_topology_bias_scatter.pdf — weighted_path_z vs bias_score per network
  fig_heatmap_{model}.pdf       — activation heatmap per model (×4)
  fig_al_differences.pdf        — AL difference distributions
  fig_edge_weight_distribution.pdf — edge-weight ECDF + bucket bars

Network figures (edge lists + activation matrices):
  fig_networks.pdf, fig_networks_ego.pdf, fig_mindset_streams.pdf
  fig_network_overview.pdf, fig_spreading_example.pdf

Run:
  python3 04_figures.py
"""

import os
import sys
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import seaborn as sns
from matplotlib.lines import Line2D
from matplotlib.collections import LineCollection
from scipy import stats

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from utils import (
    MODELS, MODEL_COLORS, MODEL_COLOR_PALETTES,
    GENDER_PAIRS, GENDER_PRIMES, PRIMES_F, PRIMES_M, TARGETS_F, TARGETS_M,
    DATA_DIR, FIGURES_DIR, STATS_DIR, ROBUSTNESS_DIR,
    load_edgelist, load_activation_matrix, normalizeDF, matricesGender,
)

# ── Global style ──────────────────────────────────────────────────────────────
plt.rcParams.update({
    "font.family":        "sans-serif",
    "font.size":          10,
    "axes.labelsize":     11,
    "axes.titlesize":     11,
    "xtick.labelsize":    9,
    "ytick.labelsize":    9,
    "legend.fontsize":    9,
    "legend.frameon":     False,
    "axes.spines.top":    False,
    "axes.spines.right":  False,
    "figure.dpi":         150,
    "savefig.dpi":        300,
    "savefig.bbox":       "tight",
    "pdf.fonttype":       42,   # embed TrueType fonts (editable in Illustrator)
})

os.makedirs(FIGURES_DIR, exist_ok=True)
COLORS = [MODEL_COLORS[m] for m in MODELS]


# ── Helpers ───────────────────────────────────────────────────────────────────

def sig_stars(p):
    """Return significance stars; empty string for non-significant."""
    if   p < 0.001: return "***"
    elif p < 0.01:  return "**"
    elif p < 0.05:  return "*"
    return ""


def bar_annotate(ax, xs, tops, pvals, ymin, ymax, fontsize=10):
    """Place significance stars above bars after ylim is set."""
    pad = 0.04 * (ymax - ymin)
    for x, top, p in zip(xs, tops, pvals):
        s = sig_stars(p)
        if s:
            ax.text(x, top + pad, s, ha="center", va="bottom",
                    fontsize=fontsize, color="black")


def panel_label(ax, lbl, x=-0.14, y=1.06):
    ax.text(x, y, lbl, transform=ax.transAxes,
            fontsize=12, fontweight="bold", va="top")


def save_fig(fig, name):
    path = os.path.join(FIGURES_DIR, name)
    fig.savefig(path)
    plt.close(fig)
    print(f"  Saved: {path}")


# ── Load all data ──────────────────────────────────────────────────────────────
topo      = pd.read_csv(os.path.join(DATA_DIR, "topology_metrics.csv")).set_index("model")
comp      = pd.read_csv(os.path.join(DATA_DIR, "topology_comparisons.csv"))
wil_F     = pd.read_csv(os.path.join(STATS_DIR, "wilcoxon_gender_F.csv"),  index_col=0)
wil_M     = pd.read_csv(os.path.join(STATS_DIR, "wilcoxon_gender_M.csv"),  index_col=0)
lme       = pd.read_csv(os.path.join(ROBUSTNESS_DIR, "robustness_weighted_path_lme.csv")).set_index("model")
topo_bias = pd.read_csv(os.path.join(DATA_DIR, "topology_bias_data.csv"))

# Lookup: comp_p[model] = {"ASPL_p": ..., "CC_uw_p": ...}
comp_p = {"Humans": {k: np.nan for k in ("ASPL_p", "CC_uw_p")}}
for _, row in comp.iterrows():
    m = row["comparison"].split(" vs ")[1]
    comp_p[m] = {"ASPL_p": row["ASPL_p"], "CC_uw_p": row["CC_uw_p"]}

print("Data loaded.\n")

# ── Build activation sub-matrices (heatmaps + AL-diff histograms) ─────────────
print("Loading activation matrices …")
_norm = {}
for m in MODELS:
    _norm[m] = normalizeDF(load_activation_matrix(f"{m}_gender"), normalize_rows=True)

_shared = set.intersection(*[set(df.index) for df in _norm.values()])
tgts_F  = [t for t in TARGETS_F if t in _shared]
tgts_M  = [t for t in TARGETS_M if t in _shared]

mat_gender = {}
al_diffs   = {}
for m in MODELS:
    df  = _norm[m]
    pF  = [p for p in PRIMES_F if p in df.columns]
    pM  = [p for p in PRIMES_M if p in df.columns]
    mF  = matricesGender(df, tgts_F, pF, pM)
    mM  = matricesGender(df, tgts_M, pF, pM)
    mat_gender[m] = {"Female-related targets": mF, "Male-related targets": mM,
                     "primes_F": pF, "primes_M": pM}
    al_diffs[m]   = {
        "Female-related targets": mF[pF].values.flatten() - mF[pM].values.flatten(),
        "Male-related targets":   mM[pM].values.flatten() - mM[pF].values.flatten(),
    }
print("Activation matrices ready.\n")


# ══════════════════════════════════════════════════════════════════════════════
# Figure 1 — Topology: ASPL, CC_weighted, CC_unweighted   (SQ1)
# ══════════════════════════════════════════════════════════════════════════════
print("Figure 1: Topology overview …")

_panels = [
    # (col, lo_col, hi_col, p_key, ylabel, ymin)
    ("ASPL",          "ASPL_CI_lo",  "ASPL_CI_hi",  "ASPL_p",
     "ASPL  (unweighted)",            1.0),
    ("CC_unweighted", "CC_uw_CI_lo", "CC_uw_CI_hi", "CC_uw_p",
     "Clustering coefficient  (unweighted)", 0.0),
]

fig, axes = plt.subplots(1, 2, figsize=(8.5, 4.5))
xs = np.arange(len(MODELS))

for ax, (col, lo_col, hi_col, p_key, ylabel, ymin), plbl in zip(
        axes, _panels, ["(a)", "(b)"]):

    vals = [topo.loc[m, col] for m in MODELS]

    ax.bar(xs, vals, color=COLORS, width=0.6, zorder=2,
           edgecolor="white", linewidth=0.5)

    if lo_col and hi_col:
        lo_err = [topo.loc[m, col] - topo.loc[m, lo_col] for m in MODELS]
        hi_err = [topo.loc[m, hi_col] - topo.loc[m, col] for m in MODELS]
        ax.errorbar(xs, vals, yerr=[lo_err, hi_err],
                    fmt="none", color="black", capsize=3.5,
                    elinewidth=1.2, capthick=1.2, zorder=3)
        tops = [v + e for v, e in zip(vals, hi_err)]
    else:
        tops = vals[:]

    ymax = max(tops) * (1.12 if ymin > 0 else 1.30) + ymin * 0.05
    ax.set_ylim(ymin, ymax)

    pvals = [comp_p[m][p_key] if m != "Humans" else np.nan for m in MODELS]
    bar_annotate(ax, xs, tops, pvals, ymin, ymax)

    ax.set_xticks(xs)
    ax.set_xticklabels(MODELS, rotation=0, ha="center")
    ax.set_ylabel(ylabel)
    ax.tick_params(axis="x", length=0)

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    panel_label(ax, plbl)

plt.tight_layout(w_pad=2.0)
save_fig(fig, "fig_topology.pdf")


# ══════════════════════════════════════════════════════════════════════════════
# Figure 2 — Gender bias effect sizes   (replication of Abramski et al. 2025)
# ══════════════════════════════════════════════════════════════════════════════
print("Figure 2: Gender bias effect sizes …")

fig, axes = plt.subplots(1, 2, figsize=(9, 4.5))

for ax, (wil, title, plbl) in zip(
        axes,
        [(wil_F, "Female-related targets", "(a)"),
         (wil_M, "Male-related targets",   "(b)")]):

    effs  = [float(wil.loc[m, "effect"]) for m in MODELS]
    pvals = [float(wil.loc[m, "p"])      for m in MODELS]

    ax.bar(xs, effs, color=COLORS, width=0.6, zorder=2,
           edgecolor="white", linewidth=0.5)

    ymax = max(effs) * 1.25
    ax.set_ylim(0, ymax)

    bar_annotate(ax, xs, effs, pvals, 0, ymax)

    ax.set_xticks(xs)
    ax.set_xticklabels(MODELS, rotation=0, ha="center")
    ax.set_ylabel("Effect size  (r)")
    ax.set_title(title)
    ax.tick_params(axis="x", length=0)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    panel_label(ax, plbl)

plt.tight_layout(w_pad=2.0)
save_fig(fig, "fig_gender_bias.pdf")


# ══════════════════════════════════════════════════════════════════════════════
# Figure 3 — LME forest plot: β for weighted_path_z per network  (SQ2)
# ══════════════════════════════════════════════════════════════════════════════
print("Figure 3: LME forest plot …")

fig, ax = plt.subplots(figsize=(7, 3.8))

# Plot reversed so Humans is at the top
y_pos = np.arange(len(MODELS) - 1, -1, -1)   # 3, 2, 1, 0

betas  = [lme.loc[m, "beta_weighted_path_z"] for m in MODELS]
ses    = [lme.loc[m, "SE"]                   for m in MODELS]
pvals  = [lme.loc[m, "p"]                    for m in MODELS]
ci95   = [1.96 * s for s in ses]

for y, m, beta, se, p, ci in zip(y_pos, MODELS, betas, ses, pvals, ci95):
    ax.errorbar(beta, y, xerr=ci,
                fmt="o", color=MODEL_COLORS[m], markersize=10,
                elinewidth=2.0, capsize=5, capthick=2.0, zorder=3)

    # p-value text
    p_str = "p < .001" if p < 0.001 else f"p = {p:.3f}"
    s     = sig_stars(p)
    ax.text(beta + ci + 0.003, y,
            f"{s}  {p_str}",
            va="center", ha="left", fontsize=8.5, color="black")

ax.axvline(0, color="black", linewidth=0.9, linestyle="--",
           alpha=0.55, zorder=1)

# Set x limits to accommodate text annotations
x_lo = min(b - c for b, c in zip(betas, ci95)) - 0.012
x_hi = max(b + c for b, c in zip(betas, ci95)) + 0.085
ax.set_xlim(x_lo, x_hi)

ax.set_yticks(y_pos)
ax.set_yticklabels(MODELS, fontsize=10)
ax.set_xlabel("β  (weighted path distance z-score → bias score)")
ax.set_title("LME: bias_score ~ weighted_path_z + (1 | prime)", fontsize=10)

# Colour swatch legend (model colours)
handles = [Line2D([0], [0], marker="o", color="w", markerfacecolor=MODEL_COLORS[m],
                  markersize=9, label=m)
           for m in MODELS]
ax.legend(handles=handles, loc="lower right", fontsize=8.5)

plt.tight_layout()
save_fig(fig, "fig_lme_forest.pdf")


# ══════════════════════════════════════════════════════════════════════════════
# Figure 4 — Topology–bias scatter: weighted_path_z vs. bias score (SQ2)
# ══════════════════════════════════════════════════════════════════════════════
print("Figure 4: Topology–bias scatter …")

fig, axes = plt.subplots(2, 2, figsize=(10, 8), sharex=False, sharey=False)
axes = axes.flatten()

# Global axis ranges for visual comparability
x_all = topo_bias["weighted_path_z"].values
y_all = topo_bias["bias_score"].values
x_pad = (x_all.max() - x_all.min()) * 0.08
y_pad = (y_all.max() - y_all.min()) * 0.08
X_LIM = (x_all.min() - x_pad, x_all.max() + x_pad)
Y_LIM = (max(0, y_all.min() - y_pad), y_all.max() + y_pad)

for ax, m, plbl in zip(axes, MODELS, ["(a)", "(b)", "(c)", "(d)"]):
    sub   = topo_bias[topo_bias["network"] == m].copy()
    x     = sub["weighted_path_z"].values
    y_val = sub["bias_score"].values

    is_F = sub["prime"].isin(PRIMES_F).values

    # Scatter: circles = female primes, triangles = male primes
    ax.scatter(x[is_F],  y_val[is_F],  color=MODEL_COLORS[m], alpha=0.45,
               s=28, marker="o", zorder=2, label="Female prime")
    ax.scatter(x[~is_F], y_val[~is_F], color=MODEL_COLORS[m], alpha=0.45,
               s=28, marker="^", zorder=2, label="Male prime")

    # OLS regression line
    slope, intercept, *_ = stats.linregress(x, y_val)
    x_line = np.linspace(x.min(), x.max(), 200)
    ax.plot(x_line, slope * x_line + intercept,
            color=MODEL_COLORS[m], linewidth=2.2, zorder=3)

    ax.set_xlim(X_LIM)
    ax.set_ylim(Y_LIM)

    ax.set_title(m, fontsize=11, fontweight="bold",
                 color=MODEL_COLORS[m])
    ax.set_xlabel("Weighted path distance  (z-scored)")
    ax.set_ylabel("Bias score")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    panel_label(ax, plbl)

# Single legend for marker types (bottom-centre of the figure)
legend_handles = [
    Line2D([0], [0], marker="o", color="gray", linestyle="None",
           markersize=7, label="Female prime"),
    Line2D([0], [0], marker="^", color="gray", linestyle="None",
           markersize=7, label="Male prime"),
    Line2D([0], [0], color="gray", linewidth=2, label="OLS regression line"),
]
fig.legend(handles=legend_handles, loc="lower center",
           ncol=3, fontsize=9, bbox_to_anchor=(0.5, -0.02))

plt.tight_layout(rect=[0, 0.04, 1, 1])
save_fig(fig, "fig_topology_bias_scatter.pdf")


# ══════════════════════════════════════════════════════════════════════════════
# Figure 5 — Activation heatmaps per model
# ══════════════════════════════════════════════════════════════════════════════
print("Figure 5: Activation heatmaps …")

for m in MODELS:
    pF  = mat_gender[m]["primes_F"]
    pM  = mat_gender[m]["primes_M"]
    mF  = mat_gender[m]["Female-related targets"][pF + pM]
    mM  = mat_gender[m]["Male-related targets"][pF + pM]

    fig, axes = plt.subplots(1, 2, figsize=(14, 8))
    fig.suptitle(m, fontsize=18, weight="bold")

    palette = MODEL_COLOR_PALETTES[m]
    sns.heatmap(mF, annot=False, cmap=palette, ax=axes[0], vmin=0, vmax=1)
    axes[0].set_title("Female-related targets ($T_F$):  $AL_p(t)$", fontsize=14)
    axes[0].set_xlabel("Primes ($p_F$, $p_M$)", fontsize=12)
    axes[0].set_ylabel("Targets ($T_F$)", fontsize=12)

    sns.heatmap(mM, annot=False, cmap=palette, ax=axes[1], vmin=0, vmax=1)
    axes[1].set_title("Male-related targets ($T_M$):  $AL_p(t)$", fontsize=14)
    axes[1].set_xlabel("Primes ($p_F$, $p_M$)", fontsize=12)
    axes[1].set_ylabel("", fontsize=12)

    plt.tight_layout()
    save_fig(fig, f"fig_heatmap_{m}.pdf")


# ══════════════════════════════════════════════════════════════════════════════
# Figure 6 — AL difference distributions
# ══════════════════════════════════════════════════════════════════════════════
print("Figure 6: AL difference histograms …")

fig, axes = plt.subplots(len(MODELS), 2, figsize=(12, 4 * len(MODELS)), sharey=True)
fig.suptitle(
    "Activation Level Differences  ($\\mathrm{Diff}_F$,  $\\mathrm{Diff}_M$)",
    fontsize=16, weight="bold")

_hist_titles = [
    "$\\mathrm{Diff}_F(t) = AL_{p_F}(t) - AL_{p_M}(t)$,  $t \\in T_F$",
    "$\\mathrm{Diff}_M(t) = AL_{p_M}(t) - AL_{p_F}(t)$,  $t \\in T_M$",
]
_hist_types = ["Female-related targets", "Male-related targets"]

for i, m in enumerate(MODELS):
    for j, ttype in enumerate(_hist_types):
        ax = axes[i, j]
        ax.hist(al_diffs[m][ttype], bins=30,
                color=MODEL_COLORS[m], edgecolor="black", alpha=0.85)
        ax.axvline(0, color="black", linewidth=1, linestyle="--")
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        if i == 0:
            ax.set_title(_hist_titles[j], fontsize=11)
        if j == 0:
            ax.set_ylabel(f"{m}\nFrequency", fontsize=11)
        if i == len(MODELS) - 1:
            ax.set_xlabel("$\\mathrm{Diff}(t)$", fontsize=11)

plt.tight_layout()
save_fig(fig, "fig_al_differences.pdf")


# ══════════════════════════════════════════════════════════════════════════════
# Figure 7 — Edge-weight distribution
# ══════════════════════════════════════════════════════════════════════════════
print("Figure 7: Edge-weight distribution …")

os.makedirs(FIGURES_DIR, exist_ok=True)
OUT = os.path.join(FIGURES_DIR, "fig_edge_weight_distribution.pdf")

# Bucket edges:  w = 2,  3,  4,  5,  6–10,  11–30,  31–100
BUCKETS = [
    ("2",       lambda w: w == 2),
    ("3",       lambda w: w == 3),
    ("4",       lambda w: w == 4),
    ("5",       lambda w: w == 5),
    ("6–10",    lambda w: (w >= 6)  & (w <= 10)),
    ("11–30",   lambda w: (w >= 11) & (w <= 30)),
    ("31–100",  lambda w: (w >= 31) & (w <= 100)),
]

weights_by_model = {}
for m in MODELS:
    g = load_edgelist(m, directed=False)
    weights_by_model[m] = np.array([d.get("weight", 1.0) for _, _, d in g.edges(data=True)])

# ── Figure ────────────────────────────────────────────────────────────────────
plt.rcParams.update({"font.family": "sans-serif", "pdf.fonttype": 42})
fig, axes = plt.subplots(1, 2, figsize=(11.5, 4.6))

# Panel A — ECDF on log x-axis
ax = axes[0]
for m in MODELS:
    w = np.sort(weights_by_model[m])
    cdf = np.arange(1, len(w) + 1) / len(w)
    ax.plot(w, cdf, color=MODEL_COLORS[m], linewidth=2.0, label=m)

ax.set_xscale("log")
ax.set_xlim(2, 110)
ax.set_xticks([2, 3, 5, 10, 20, 50, 100])
ax.get_xaxis().set_major_formatter(plt.ScalarFormatter())
ax.set_xlabel("Edge weight  (response frequency)")
ax.set_ylabel("Cumulative fraction of edges")
ax.set_title("(a)  ECDF of edge weights", fontsize=11, loc="left", weight="bold")
ax.grid(alpha=0.25, linewidth=0.6)
ax.legend(loc="lower right", fontsize=9, frameon=False)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# Panel B — Stacked bar of bucket proportions
ax = axes[1]
xs = np.arange(len(MODELS))

# Build matrix: rows = buckets, cols = models
mat = np.zeros((len(BUCKETS), len(MODELS)))
for j, m in enumerate(MODELS):
    w = weights_by_model[m]
    for i, (_, pred) in enumerate(BUCKETS):
        mat[i, j] = 100.0 * pred(w).mean()

bucket_palette = plt.cm.viridis(np.linspace(0.05, 0.92, len(BUCKETS)))

bottom = np.zeros(len(MODELS))
for i, (lbl, _) in enumerate(BUCKETS):
    ax.bar(xs, mat[i], bottom=bottom, width=0.6,
           color=bucket_palette[i], edgecolor="white", linewidth=0.5, label=lbl)
    # Inline labels for slices ≥ 5 %
    for j, val in enumerate(mat[i]):
        if val >= 5:
            ax.text(xs[j], bottom[j] + val / 2,
                    f"{val:.0f}%", ha="center", va="center",
                    fontsize=8, color="white" if i >= 4 else "black")
    bottom += mat[i]

ax.set_xticks(xs)
ax.set_xticklabels(MODELS)
ax.set_ylim(0, 100)
ax.set_ylabel("% of edges")
ax.set_title("(b)  Weight bucket distribution", fontsize=11, loc="left", weight="bold")
ax.legend(title="Edge weight",
          bbox_to_anchor=(1.02, 1), loc="upper left",
          fontsize=8.5, title_fontsize=9, frameon=False)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

fig.tight_layout()
fig.savefig(OUT, bbox_inches="tight", dpi=300)
plt.close()
print(f"Saved: {OUT}")


# ══════════════════════════════════════════════════════════════════════════════
# Figures 8 — Semantic network visualisations
# ══════════════════════════════════════════════════════════════════════════════
SEED_PRIMES   = set(GENDER_PRIMES)
SEED_TARGET_F = set(TARGETS_F)
SEED_TARGET_M = set(TARGETS_M)

NODE_COLOR_TARGET_F = "#F0A0B8"
NODE_COLOR_TARGET_M = "#88C4E0"
NODE_COLOR_OTHER    = "#D0D0D0"


# ─────────────────────────────────────────────────────────────────────────────
# Figure 1 — Shell layout networks
# ─────────────────────────────────────────────────────────────────────────────
def compact_subgraph(g, top_targets_per_prime=3, top_fill=4):
    in_g  = set(g.nodes())
    wdeg  = dict(g.degree(weight="weight"))
    keep  = set(SEED_PRIMES) & in_g
    for prime in SEED_PRIMES:
        if prime not in in_g:
            continue
        nbrs = dict(g[prime])
        f_nbrs = sorted([(t, nbrs[t].get("weight", 0)) for t in SEED_TARGET_F if t in nbrs],
                        key=lambda x: x[1], reverse=True)[:top_targets_per_prime]
        m_nbrs = sorted([(t, nbrs[t].get("weight", 0)) for t in SEED_TARGET_M if t in nbrs],
                        key=lambda x: x[1], reverse=True)[:top_targets_per_prime]
        keep.update(t for t, _ in f_nbrs + m_nbrs)
    fill = sorted(in_g - keep - (SEED_TARGET_F | SEED_TARGET_M),
                  key=lambda n: wdeg.get(n, 0), reverse=True)[:top_fill]
    keep.update(fill)
    return g.subgraph(list(keep)), wdeg


def shell_pos(sub):
    """
    Concentric shell layout:
      shell 0 (inner)  — gender primes
      shell 1 (middle) — female targets (left half) + male targets (right half)
      shell 2 (outer)  — fill words
    """
    primes  = [n for n in sub.nodes() if n in SEED_PRIMES]
    t_F     = [n for n in sub.nodes() if n in SEED_TARGET_F]
    t_M     = [n for n in sub.nodes() if n in SEED_TARGET_M]
    others  = [n for n in sub.nodes() if n not in SEED_PRIMES
               and n not in SEED_TARGET_F and n not in SEED_TARGET_M]

    def ring(nodes, radius, start_angle=0, end_angle=2 * np.pi):
        n = len(nodes)
        if n == 0:
            return {}
        angles = np.linspace(start_angle, end_angle, n, endpoint=False)
        return {nd: (radius * np.cos(a), radius * np.sin(a))
                for nd, a in zip(nodes, angles)}

    pos = {}
    pos.update(ring(primes, 0.35))
    # Female targets on left half (pi/2 → 3pi/2), male on right (−pi/2 → pi/2)
    pos.update(ring(t_F, 0.72, start_angle=np.pi / 2, end_angle=3 * np.pi / 2))
    pos.update(ring(t_M, 0.72, start_angle=-np.pi / 2, end_angle=np.pi / 2))
    pos.update(ring(others, 1.08))
    return pos


print("Figure 8a: Shell-layout core networks …")
fig, axes = plt.subplots(2, 2, figsize=(14, 13))
axes = axes.flatten()

for ax, model in zip(axes, MODELS):
    print(f"  {model} …", end=" ", flush=True)
    g = load_edgelist(model, directed=False)
    sub, wdeg = compact_subgraph(g, top_targets_per_prime=3, top_fill=4)
    pos      = shell_pos(sub)
    max_wdeg = max((wdeg.get(n, 1) for n in sub.nodes()), default=1)

    # edges
    edges = sorted(sub.edges(data=True), key=lambda e: e[2].get("weight", 0), reverse=True)[:120]
    segs  = [[pos[u], pos[v]] for u, v, _ in edges if u in pos and v in pos]
    if segs:
        ax.add_collection(LineCollection(segs, linewidths=0.55, colors="#999999",
                                         alpha=0.35, zorder=1))

    # node groups
    primes = [n for n in sub.nodes() if n in SEED_PRIMES]
    t_F    = [n for n in sub.nodes() if n in SEED_TARGET_F]
    t_M    = [n for n in sub.nodes() if n in SEED_TARGET_M]
    others = [n for n in sub.nodes() if n not in SEED_PRIMES
              and n not in SEED_TARGET_F and n not in SEED_TARGET_M]

    def scat(nodes, color, s_min, s_max, ec="white", lw=0.0, alpha=1.0, zo=2):
        if not nodes:
            return
        xs  = [pos[n][0] for n in nodes if n in pos]
        ys  = [pos[n][1] for n in nodes if n in pos]
        szs = [s_min + (s_max - s_min) *
               (np.log1p(wdeg.get(n, 0)) / np.log1p(max(max_wdeg, 1)))
               for n in nodes if n in pos]
        ax.scatter(xs, ys, s=szs, c=color, edgecolors=ec, linewidths=lw,
                   alpha=alpha, zorder=zo)

    scat(others, NODE_COLOR_OTHER, 25, 130, ec="none", alpha=0.65)
    scat(t_F,    NODE_COLOR_TARGET_F, 55, 220, lw=0.8, alpha=0.90, zo=3)
    scat(t_M,    NODE_COLOR_TARGET_M, 55, 220, lw=0.8, alpha=0.90, zo=3)
    scat(primes, MODEL_COLORS[model], 130, 400, lw=1.8, alpha=1.0, zo=4)

    # labels
    for n in primes:
        if n not in pos: continue
        x, y = pos[n]
        ax.text(x, y, n, fontsize=7.5, ha="center", va="center",
                fontweight="bold", color="white", zorder=6,
                bbox=dict(boxstyle="round,pad=0.15", facecolor=MODEL_COLORS[model],
                          edgecolor="none", alpha=0.85))
    for n in t_F:
        if n not in pos: continue
        x, y = pos[n]
        ax.text(x - 0.04, y, n, fontsize=6.0, ha="right", va="center",
                color="#8B0040", zorder=5)
    for n in t_M:
        if n not in pos: continue
        x, y = pos[n]
        ax.text(x + 0.04, y, n, fontsize=6.0, ha="left", va="center",
                color="#003880", zorder=5)
    for n in others:
        if n not in pos: continue
        x, y = pos[n]
        ax.text(x, y + 0.06, n, fontsize=5.5, ha="center", va="bottom",
                color="#555555", zorder=5)

    ax.set_xlim(-1.35, 1.35)
    ax.set_ylim(-1.35, 1.35)
    ax.set_aspect("equal")
    ax.axis("off")
    ax.set_title(f"{model}\n{g.number_of_nodes():,} nodes · {g.number_of_edges():,} edges",
                 color=MODEL_COLORS[model], fontsize=11, fontweight="bold", pad=7)
    print("done")

legend_handles = [
    Line2D([0],[0], marker="o", linestyle="None", color="w",
           markerfacecolor="#555555", markeredgecolor="white", markersize=11,
           label="Gender prime (model colour)"),
    Line2D([0],[0], marker="o", linestyle="None", color="w",
           markerfacecolor=NODE_COLOR_TARGET_F, markeredgecolor="white", markersize=10,
           label="Female stereotype target"),
    Line2D([0],[0], marker="o", linestyle="None", color="w",
           markerfacecolor=NODE_COLOR_TARGET_M, markeredgecolor="white", markersize=10,
           label="Male stereotype target"),
    Line2D([0],[0], marker="o", linestyle="None", color="w",
           markerfacecolor=NODE_COLOR_OTHER, markeredgecolor="none", markersize=8,
           label="High-frequency word"),
]
fig.legend(handles=legend_handles, loc="lower center", ncol=4, fontsize=9.5,
           bbox_to_anchor=(0.5, -0.01), handletextpad=0.5, columnspacing=1.0)
fig.suptitle("Semantic network clusters  ·  Gender primes (inner) → stereotype targets (middle ring) → fill words (outer)\n"
             "Node size ∝ log(weighted degree)  ·  Top-120 strongest edges shown",
             fontsize=10, y=1.01, color="#555555")
plt.tight_layout(rect=[0, 0.04, 1, 1])
out = os.path.join(FIGURES_DIR, "fig_networks.pdf")
fig.savefig(out, bbox_inches="tight")
plt.close(fig)
print(f"  Saved: {out}\n")


# ─────────────────────────────────────────────────────────────────────────────
# Figure 2 — Ego network using activation strength (not direct edges)
# ─────────────────────────────────────────────────────────────────────────────
print("Figure 8b: Activation-based ego networks …")

fig2, axes2 = plt.subplots(2, 2, figsize=(14, 12))
axes2 = axes2.flatten()

for ax, model in zip(axes2, MODELS):
    print(f"  {model} …", end=" ", flush=True)
    g       = load_edgelist(model, directed=False)
    df_norm = normalizeDF(load_activation_matrix(f"{model}_gender"), normalize_rows=True)
    in_g    = set(g.nodes())
    wdeg    = dict(g.degree(weight="weight"))

    pf = [p for p in PRIMES_F if p in in_g and p in df_norm.columns]
    pm = [p for p in PRIMES_M if p in in_g and p in df_norm.columns]
    tf = [t for t in TARGETS_F if t in in_g and t in df_norm.index]
    tm = [t for t in TARGETS_M if t in in_g and t in df_norm.index]

    # Sort targets by total activation from all primes
    tf_sorted = sorted(tf, key=lambda t: df_norm.loc[t, pf + pm].sum(), reverse=True)
    tm_sorted = sorted(tm, key=lambda t: df_norm.loc[t, pf + pm].sum(), reverse=True)

    # Fixed bipartite positions
    x_tf, x_pf, x_pm, x_tm = -1.5, -0.5, 0.5, 1.5

    def col_y(items, h=3.0):
        n = len(items)
        return [h/2 - h*i/max(n-1, 1) for i in range(n)] if n > 0 else []

    pos = {}
    for nd, y in zip(tf_sorted, col_y(tf_sorted)): pos[nd] = (x_tf, y)
    for nd, y in zip(pf, col_y(pf)):               pos[nd] = (x_pf, y)
    for nd, y in zip(pm, col_y(pm)):               pos[nd] = (x_pm, y)
    for nd, y in zip(tm_sorted, col_y(tm_sorted)): pos[nd] = (x_tm, y)

    # Collect activation-based edges (AL_prime(target) from df_norm)
    al_edges = []
    for p in pf:
        for t in tf_sorted:
            al = float(df_norm.loc[t, p])
            al_edges.append((p, t, al, "F"))
    for p in pm:
        for t in tm_sorted:
            al = float(df_norm.loc[t, p])
            al_edges.append((p, t, al, "M"))

    # Threshold: top 35% by activation level
    all_als = [e[2] for e in al_edges]
    thresh  = np.percentile(all_als, 65)
    draw_edges = [e for e in al_edges if e[2] >= thresh]
    max_al     = max(e[2] for e in draw_edges) if draw_edges else 1.0

    for p, t, al, gender in draw_edges:
        norm = al / max_al
        lw    = 0.4 + 3.5 * norm ** 0.6
        alpha = 0.20 + 0.65 * norm ** 0.5
        color = "#C06080" if gender == "F" else "#4080B0"
        ax.plot([pos[p][0], pos[t][0]], [pos[p][1], pos[t][1]],
                color=color, linewidth=lw, alpha=alpha, zorder=1)

    # Nodes
    max_wdeg = max((wdeg.get(n, 1) for n in pos), default=1)

    def scat2(nodes, color, s_min, s_max, zo=3):
        if not nodes: return
        xs  = [pos[n][0] for n in nodes if n in pos]
        ys  = [pos[n][1] for n in nodes if n in pos]
        szs = [s_min + (s_max - s_min) *
               (np.log1p(wdeg.get(n, 0)) / np.log1p(max(max_wdeg, 1)))
               for n in nodes if n in pos]
        ax.scatter(xs, ys, s=szs, c=color, edgecolors="white", linewidths=0.8,
                   alpha=0.90, zorder=zo)

    scat2(tf_sorted, NODE_COLOR_TARGET_F, 55, 190)
    scat2(tm_sorted, NODE_COLOR_TARGET_M, 55, 190)
    scat2(pf + pm,   MODEL_COLORS[model], 140, 450, zo=4)

    # Labels
    for n in pf + pm:
        x, y = pos[n]
        ax.text(x, y, n, fontsize=7.5, ha="center", va="center",
                fontweight="bold", color="white", zorder=6,
                bbox=dict(boxstyle="round,pad=0.18", facecolor=MODEL_COLORS[model],
                          edgecolor="none", alpha=0.88))
    for n in tf_sorted:
        x, y = pos[n]
        ax.text(x - 0.08, y, n, fontsize=5.8, ha="right", va="center",
                color="#7A0030", zorder=5)
    for n in tm_sorted:
        x, y = pos[n]
        ax.text(x + 0.08, y, n, fontsize=5.8, ha="left", va="center",
                color="#003880", zorder=5)

    for x_col, label, col in [(x_tf, "Female targets", "#E07090"),
                               (x_pf, "Female primes",  MODEL_COLORS[model]),
                               (x_pm, "Male primes",    MODEL_COLORS[model]),
                               (x_tm, "Male targets",   "#4090C0")]:
        ax.text(x_col, 1.72, label, ha="center", va="bottom",
                fontsize=7.5, color=col, fontweight="bold")

    ax.set_xlim(x_tf - 0.55, x_tm + 0.55)
    ax.set_ylim(-1.85, 1.90)
    ax.set_aspect("auto")
    ax.axis("off")
    ax.set_title(f"{model}\n{len(pf+pm)} primes · {len(tf)+len(tm)} targets · "
                 f"{len(draw_edges)} activation edges shown (top 35 %)",
                 color=MODEL_COLORS[model], fontsize=11, fontweight="bold", pad=7)
    print("done")

legend2 = [
    Line2D([0],[0], marker="o", linestyle="None", color="w",
           markerfacecolor="#555555", markeredgecolor="white", markersize=12,
           label="Gender prime (model colour)"),
    Line2D([0],[0], marker="o", linestyle="None", color="w",
           markerfacecolor=NODE_COLOR_TARGET_F, markeredgecolor="white", markersize=10,
           label="Female stereotype target"),
    Line2D([0],[0], marker="o", linestyle="None", color="w",
           markerfacecolor=NODE_COLOR_TARGET_M, markeredgecolor="white", markersize=10,
           label="Male stereotype target"),
    Line2D([0],[0], color="#C06080", linewidth=2.5,
           label="Female-prime edge (width ∝ activation strength)"),
    Line2D([0],[0], color="#4080B0", linewidth=2.5,
           label="Male-prime edge (width ∝ activation strength)"),
]
fig2.legend(handles=legend2, loc="lower center", ncol=3, fontsize=9.0,
            bbox_to_anchor=(0.5, -0.01), handletextpad=0.5, columnspacing=1.1)
fig2.suptitle("Gender ego networks  ·  Edge width ∝ normalised activation level AL_prime(target)\n"
              "Top 35 % of activation-strength edges shown per panel",
              fontsize=10, y=1.01, color="#555555")
plt.tight_layout(rect=[0, 0.06, 1, 1])
out2 = os.path.join(FIGURES_DIR, "fig_networks_ego.pdf")
fig2.savefig(out2, bbox_inches="tight")
plt.close(fig2)
print(f"  Saved: {out2}\n")


# ─────────────────────────────────────────────────────────────────────────────
# Figure 3 — Mindset streams
# Shortest weighted paths (1/w) for 4 prime-target pairs per source.
# ─────────────────────────────────────────────────────────────────────────────
print("Figure 8c: Mindset streams …")

STREAM_PAIRS = [
    ("feminine", "compassionate", True,  "Stereotype-consistent (F)"),
    ("feminine", "forceful",      False, "Stereotype-inconsistent (F)"),
    ("masculine","forceful",      True,  "Stereotype-consistent (M)"),
    ("masculine","compassionate", False, "Stereotype-inconsistent (M)"),
]

fig3, axes3 = plt.subplots(len(MODELS), len(STREAM_PAIRS),
                            figsize=(16, 4.5 * len(MODELS)))

for row, model in enumerate(MODELS):
    g = load_edgelist(model, directed=False)
    g_dist = g.copy()
    for u, v, d in g_dist.edges(data=True):
        w = d.get("weight", 1.0)
        g_dist[u][v]["distance"] = 1.0 / w if w > 0 else float("inf")

    for col, (prime, target, consistent, pair_label) in enumerate(STREAM_PAIRS):
        ax = axes3[row, col]
        ax.axis("off")

        if prime not in g_dist or target not in g_dist:
            ax.set_title(f"{prime} → {target}\n(not in network)", fontsize=9)
            continue
        try:
            path = nx.shortest_path(g_dist, prime, target, weight="distance")
        except (nx.NetworkXNoPath, nx.NodeNotFound):
            ax.set_title(f"{prime} → {target}\n(no path)", fontsize=9)
            continue

        # Build path subgraph
        path_g = nx.Graph()
        for i in range(len(path) - 1):
            u, v = path[i], path[i+1]
            w = g[u][v].get("weight", 1) if g.has_edge(u, v) else 1
            path_g.add_edge(u, v, weight=w)

        # Linear layout: space nodes evenly left to right
        n = len(path)
        path_pos = {nd: (i / max(n - 1, 1), 0.0) for i, nd in enumerate(path)}

        # Draw edges with width ∝ weight
        max_w = max((path_g[u][v].get("weight", 1)
                     for u, v in path_g.edges()), default=1)
        for u, v in path_g.edges():
            w = path_g[u][v].get("weight", 1)
            lw = 1.0 + 5.0 * (w / max_w) ** 0.5
            ax.plot([path_pos[u][0], path_pos[v][0]],
                    [path_pos[u][1], path_pos[v][1]],
                    color="#888888", linewidth=lw, alpha=0.7, zorder=1,
                    solid_capstyle="round")

        # Draw nodes
        for nd in path:
            x, y = path_pos[nd]
            if nd == prime:
                color = MODEL_COLORS[model]
                size  = 220
            elif nd == target:
                color = NODE_COLOR_TARGET_F if target in SEED_TARGET_F else NODE_COLOR_TARGET_M
                size  = 200
            else:
                color = "#E8E8E8"
                size  = 140
            ax.scatter(x, y, s=size, c=color, edgecolors="white", linewidths=1.2,
                       zorder=3)

        # Labels above/below alternating to avoid overlap
        for i, nd in enumerate(path):
            x, y = path_pos[nd]
            offset = 0.14 if i % 2 == 0 else -0.14
            va     = "bottom" if offset > 0 else "top"
            fw     = "bold" if nd in (prime, target) else "normal"
            ax.text(x, y + offset, nd, ha="center", va=va,
                    fontsize=7.5 if nd in (prime, target) else 6.5,
                    fontweight=fw, color="black", zorder=5)

        border_color = MODEL_COLORS[model] if consistent else "#999999"
        for spine in ax.spines.values():
            spine.set_visible(True)
            spine.set_edgecolor(border_color)
            spine.set_linewidth(2.0 if consistent else 1.0)

        ax.set_xlim(-0.18, 1.18)
        ax.set_ylim(-0.45, 0.45)

        title = f"{prime} → {target}  ({len(path)-1} hops)"
        if row == 0:
            ax.set_title(f"{pair_label}\n{title}", fontsize=9,
                         color=border_color, fontweight="bold" if consistent else "normal")
        else:
            ax.set_title(title, fontsize=9, color=border_color,
                         fontweight="bold" if consistent else "normal")

    # Row label
    axes3[row, 0].set_ylabel(model, fontsize=11, fontweight="bold",
                              color=MODEL_COLORS[model], rotation=90,
                              labelpad=8)

fig3.suptitle(
    'Mindset streams  ·  Shortest weighted paths (distance = 1/weight) between prime and target\n'
    'Bold border = stereotype-consistent pair  ·  Node size: prime (large) / intermediate / target',
    fontsize=10, y=1.01, color="#555555",
)
plt.tight_layout()
out3 = os.path.join(FIGURES_DIR, "fig_mindset_streams.pdf")
fig3.savefig(out3, bbox_inches="tight")
plt.close(fig3)
print(f"  Saved: {out3}\n")

print("Network figures complete.")


# ══════════════════════════════════════════════════════════════════════════════
# Figures 9 — Additional network visualisations
# ══════════════════════════════════════════════════════════════════════════════
ALL_TARGETS = set(TARGETS_F) | set(TARGETS_M)
ALL_PRIMES  = set(GENDER_PRIMES)


# ─────────────────────────────────────────────────────────────────────────────
# Figure 1 — General structural overview
# ─────────────────────────────────────────────────────────────────────────────
print("Figure 9a: General structural overview …")

TOP_N      = 60    # highest-degree nodes to include
LABEL_TOP  = 15   # how many to label
TOP_EDGES  = 200   # strongest edges to draw

fig, axes = plt.subplots(2, 2, figsize=(15, 14))
axes = axes.flatten()

for ax, model in zip(axes, MODELS):
    print(f"  {model} …", end=" ", flush=True)
    g    = load_edgelist(model, directed=False)
    wdeg = dict(g.degree(weight="weight"))

    # Select top-N nodes by weighted degree
    top_nodes = sorted(wdeg, key=wdeg.get, reverse=True)[:TOP_N]
    sub = g.subgraph(top_nodes)

    # Kamada-Kawai layout — minimises edge crossing, shows structure well
    try:
        pos = nx.kamada_kawai_layout(sub, weight="weight")
    except Exception:
        pos = nx.spring_layout(sub, seed=42, k=2.5/np.sqrt(len(sub)), iterations=200)

    # Node sizes and colours by log(wdeg)
    log_deg    = np.array([np.log1p(wdeg[n]) for n in sub.nodes()])
    norm_deg   = (log_deg - log_deg.min()) / (log_deg.max() - log_deg.min() + 1e-9)
    sizes      = 60 + 500 * norm_deg ** 1.2

    # Use model colour palette (light→dark)
    cmap       = plt.get_cmap(MODEL_COLOR_PALETTES[model])
    node_cols  = [cmap(0.25 + 0.65 * v) for v in norm_deg]

    # Draw top edges
    edges_sorted = sorted(sub.edges(data=True),
                          key=lambda e: e[2].get("weight", 0), reverse=True)[:TOP_EDGES]
    for u, v, d in edges_sorted:
        if u not in pos or v not in pos:
            continue
        w     = d.get("weight", 1)
        max_w = max(wdeg.values())
        alpha = 0.10 + 0.35 * (w / max_w) ** 0.4
        ax.plot([pos[u][0], pos[v][0]], [pos[u][1], pos[v][1]],
                color="#888888", linewidth=0.5, alpha=alpha, zorder=1)

    # Draw nodes
    xs   = [pos[n][0] for n in sub.nodes()]
    ys   = [pos[n][1] for n in sub.nodes()]
    ax.scatter(xs, ys, s=sizes, c=node_cols, edgecolors="white",
               linewidths=0.6, alpha=0.92, zorder=2)

    # Label top-LABEL_TOP nodes
    label_nodes = sorted(sub.nodes(), key=lambda n: wdeg[n], reverse=True)[:LABEL_TOP]
    for n in label_nodes:
        if n not in pos:
            continue
        x, y = pos[n]
        is_prime  = n in ALL_PRIMES
        is_target = n in ALL_TARGETS
        fw    = "bold" if is_prime else "normal"
        color = "#1a1a1a" if is_prime else ("#8B0040" if n in set(TARGETS_F)
                                            else ("#003880" if n in set(TARGETS_M)
                                                  else "#333333"))
        ax.text(x, y + 0.04, n, fontsize=6.5 if not is_prime else 7.5,
                ha="center", va="bottom", fontweight=fw, color=color,
                zorder=4,
                bbox=dict(boxstyle="round,pad=0.10", facecolor="white",
                          edgecolor="none", alpha=0.65) if is_prime else None)

    xs_arr = np.array(xs); ys_arr = np.array(ys)
    margin = 0.15
    ax.set_xlim(xs_arr.min()-margin, xs_arr.max()+margin)
    ax.set_ylim(ys_arr.min()-margin, ys_arr.max()+margin)
    ax.set_aspect("equal")
    ax.axis("off")
    ax.set_title(
        f"{model}\n"
        f"Top {TOP_N} words by weighted degree  ·  "
        f"{g.number_of_nodes():,} nodes / {g.number_of_edges():,} edges total",
        color=MODEL_COLORS[model], fontsize=11, fontweight="bold", pad=7,
    )

    # Inline colourbar
    sm = plt.cm.ScalarMappable(cmap=cmap,
                                norm=mcolors.Normalize(vmin=0, vmax=1))
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, fraction=0.03, pad=0.02, shrink=0.55)
    cbar.set_label("log(weighted degree),\nnormalised", fontsize=7)
    cbar.ax.tick_params(labelsize=6)
    print("done")

fig.suptitle(
    f"Semantic network structure  ·  Top-{TOP_N} nodes by weighted degree\n"
    "Node size & colour ∝ log(weighted degree)  ·  Kamada-Kawai layout",
    fontsize=10.5, y=1.01, color="#555555",
)
plt.tight_layout()
out1 = os.path.join(FIGURES_DIR, "fig_network_overview.pdf")
fig.savefig(out1, bbox_inches="tight")
plt.close(fig)
print(f"  Saved: {out1}\n")


# ─────────────────────────────────────────────────────────────────────────────
# Figure 2 — Spreading activation example: woman/man → doctor
#
# Shows the actual shortest weighted path (distance = 1/weight) from woman
# and man to doctor in each network.  Each panel is a left-to-right node
# chain; nodes are coloured by their normalised activation level after
# spreading from the prime.  The AL(doctor) value is annotated on the
# target node.  Directly replicates the spirit of Abramski et al. Fig. 1.
# ─────────────────────────────────────────────────────────────────────────────
print("Figure 9b: Spreading activation example (woman/man → doctor) …")

TARGET = "doctor"

fig2, axes2 = plt.subplots(len(MODELS), 2, figsize=(14, 3.8 * len(MODELS)))

for row, model in enumerate(MODELS):
    g       = load_edgelist(model, directed=False)
    df_norm = normalizeDF(load_activation_matrix(f"{model}_gender"), normalize_rows=True)

    # Build distance graph (1/weight)
    g_dist = g.copy()
    for u, v, d in g_dist.edges(data=True):
        w = d.get("weight", 1.0)
        g_dist[u][v]["distance"] = 1.0 / w if w > 0 else float("inf")

    for col, prime in enumerate(["woman", "man"]):
        ax = axes2[row, col]
        ax.axis("off")

        # Shortest weighted path
        try:
            path = nx.shortest_path(g_dist, prime, TARGET, weight="distance")
        except (nx.NetworkXNoPath, nx.NodeNotFound):
            ax.text(0.5, 0.5, "no path", ha="center", transform=ax.transAxes)
            continue

        # Activation levels for every node on the path
        al = {}
        for n in path:
            if prime in df_norm.columns and n in df_norm.index:
                al[n] = float(df_norm.loc[n, prime])
            else:
                al[n] = 0.0
        max_al = max(al.values()) if al else 1.0

        cmap_obj = plt.get_cmap(MODEL_COLOR_PALETTES[model])

        # Fixed linear positions: evenly spaced left to right
        n     = len(path)
        x_pos = np.linspace(0, 1, n)
        pos   = {nd: (x_pos[i], 0.0) for i, nd in enumerate(path)}

        # Edges (sequential path edges)
        for i in range(n - 1):
            u, v = path[i], path[i + 1]
            w = g[u][v].get("weight", 1) if g.has_edge(u, v) else 1
            max_w = max(g[path[j]][path[j+1]].get("weight",1)
                        for j in range(n-1) if g.has_edge(path[j],path[j+1])) or 1
            lw = 1.5 + 5.0 * (w / max_w) ** 0.5
            ax.annotate("", xy=pos[v], xytext=pos[u],
                        arrowprops=dict(arrowstyle="-|>",
                                        color="#999999", lw=lw,
                                        mutation_scale=14),
                        zorder=1)

        # Nodes
        for i, nd in enumerate(path):
            x, y   = pos[nd]
            norm_v = al[nd] / max_al if max_al > 0 else 0
            color  = cmap_obj(0.15 + 0.80 * norm_v)

            if nd == prime:
                size = 600; ec = MODEL_COLORS[model]; lw_ec = 3.0
            elif nd == TARGET:
                size = 500; ec = "#333333"; lw_ec = 2.5
            else:
                size = 180 + 280 * norm_v; ec = "white"; lw_ec = 1.0

            ax.scatter(x, y, s=size, c=[color], edgecolors=ec,
                       linewidths=lw_ec, zorder=3, clip_on=False)

        # Labels — alternate above/below to avoid overlap
        for i, nd in enumerate(path):
            x, y  = pos[nd]
            above = (i % 2 == 0)
            yoff  = 0.18 if above else -0.18
            va    = "bottom" if above else "top"
            fw    = "bold" if nd in (prime, TARGET) else "normal"
            fs    = 9 if nd in (prime, TARGET) else 7.5

            ax.text(x, y + yoff, nd, ha="center", va=va,
                    fontsize=fs, fontweight=fw, color="#111111", zorder=5)

            # AL annotation on target
            if nd == TARGET:
                al_val = al[nd]
                side_y = y - yoff   # opposite side from name label
                side_va = "top" if above else "bottom"
                ax.text(x, side_y, f"AL = {al_val:.3f}",
                        ha="center", va=side_va, fontsize=8, color="#333333",
                        bbox=dict(boxstyle="round,pad=0.15", facecolor="white",
                                  edgecolor="#999999", linewidth=1.0, alpha=0.90),
                        zorder=6)

        ax.set_xlim(-0.12, 1.12)
        ax.set_ylim(-0.55, 0.55)
        ax.set_aspect("auto")
        ax.set_title(
            f'"{prime}" → "{TARGET}"  ({len(path)-1} hops)',
            fontsize=10, color=MODEL_COLORS[model], fontweight="bold", pad=5,
        )

    axes2[row, 0].set_ylabel(model, fontsize=11, fontweight="bold",
                              color=MODEL_COLORS[model], labelpad=8)

fig2.suptitle(
    f'"woman" vs "man" → "doctor"  ·  Shortest weighted path per network\n'
    'Node colour intensity ∝ AL_prime(node)  ·  Arrows follow path direction',
    fontsize=10.5, y=1.01, color="#555555",
)
plt.tight_layout()
out2 = os.path.join(FIGURES_DIR, "fig_spreading_example.pdf")
fig2.savefig(out2, bbox_inches="tight")
plt.close(fig2)
print(f"  Saved: {out2}\n")

print("Extra network figures complete.")

print("\nAll figures saved to", FIGURES_DIR)
